### ISSUE TITLE
建议可以去掉百分比的开关 || 设置高度

### ISSUE THREAD

**Issue by n0tssss** [luoxmc/secret-reader#1]
如图，百分比会多出来一小部分，框的高度也无法拉到一行文字的大小
建议有个去掉百分比的开关或者允许随意拖动窗口高度到最小的一行文字
又或者支持百分比与文字展示到一行
![iShot_2022-09-22_15 31 41](https://user-images.githubusercontent.com/34975071/191685936-0f80f59e-fca0-4278-a807-bbfedd2b1112.png)

**Comment by luoxmc** [comment]
可以的，这个项目的第一个issuse，今天就给你安排上

**Comment by luoxmc** [comment]
抱歉，我调试了一波，发现这个窗口的高度没办法缩小到足够小并不是百分比造成的，就算移除百分比，窗口也没办法调得更小，我猜测是因为窗口有一个隐藏的title-bar（最小化、最大化、关闭的那个菜单栏）占用了体积，导致无法把窗口调整到足够小。我查阅了api，暂时没有办法解决这个问题。
建议先把字体稍微调大一点以改善观感。

**Comment by n0tssss** [comment]
不用这么客气哈哈，那我有空也去研究一下你的作品试试看能不能完善一下这个哈哈，我的 vscode 全屏的时候它因为高度问题无法完美的放在最下面，而是因为底部空白占了会被系统挤开，或许支持一下文本全部放在最下面可以解决我这个问题
![image](https://user-images.githubusercontent.com/34975071/191702801-4e927ecd-75ca-4316-9a65-1115c4445a5d.png)

**Comment by luoxmc** [comment]
我发现手动拖拽调整的时候，窗口大小因为那个隐藏的红绿灯占用了空间无法把窗口调整到足够小。但是创建窗口的时候程序里面设置足够小的窗口大小，是可以生成足够小的窗口的。我准备加上一个设置可以自己填写窗口大小的数字，这样就能把高度设置的足够小了。准备明天修改这个然后发布。

**Comment by n0tssss** [comment]
可以的哈哈，我都还在想直接把内容和百分比都放在窗口最下面，也能解决这个问题哈哈，但是你能完美解决就更好了啦，辛苦！

**Comment by luoxmc** [comment]
已经修改完成了，代码已提交，顺便打了个包，下载地址 https://pan.luoxx.top/s/wGIz
待会会发到utools插件市场，不过审核估计要蛮久。

ps: 虽然现在能够把窗口调整到足够小了，但是把窗口拖到屏幕底部（dock栏那里）后窗口依然还是会往上弹一小截，导致窗口无法严丝合缝的和dock栏贴合着。暂时还没找到解决方案，待修复。
